### PR TITLE
Refactors, `attrs` implementation, and unit tests

### LINKED ISSUE #3: Create Electrolyzer model unit tests
_This is to follow #2_

Create an initial suite of unit tests for the electrolyzer model. Ideally this will test the public-facing functions of the `Electrolyzer` class to ensure adequate code coverage. The control scheme tests likely fall into more of an integration testing scheme, though we may be able to unit test using fixtures and mocks.

Update this issue with unit test case information as needed.

### LINKED ISSUE #12: Rework classes to use `attrs` package
**Is your feature request related to a problem? Please describe.**
<A clear and concise description of the problem.>

Our workflow will involve validating configuration files which will then be used to instantiate Python classes representing electrolyzer operations, control, and costing. We want to ensure that this code flow is as streamlined as possible, both for the developer as well as the end user.

**Describe the solution you'd like**
<A clear and concise description of what you want to happen.>

FLORIS uses [attrs](https://www.attrs.org/en/stable/index.html), a package that makes Python class definition, instantiation, and type-checking easier. Consider using this in conjunction with `mypy` to enforce static type-checking on our classes. This requires more initial overhead, but will prove beneficial to developers in the long run.

**Describe alternatives you've considered**
<A clear and concise description of any alternative solutions or features youve considered.>

This is less crucial than #11, but may work nicely in tandem with it. If so, we may want to consider implementing this BEFORE #11, so that we have the interface we want before defining the configuration schema. 

**Additional context**
<Add any other context or screenshots about the feature request here.>

### PR DESCRIPTION
**Pull request by camirmas**
**Feature or improvement description**

**Related issue, if one exists**

resolves #3 
resolves #12 

_note: Some additional tests will be required for `Supervisor`, but this PR is already getting too large._

**Impacted areas of the software**

This is a major change that reworks the interfaces and definitions of our electrolyzer system.

This PR proposes a system composed of three primary classes within the `electrolyzer` package:
- `Supervisor`: control operations for a system of electrolyzers. As before, it instantiates numerous electrolyzer instances, though these are now called `Stack`
- `Stack`: control operations for an individual electrolyzer stack. This class relies upon a single `Cell` instance to perform electrochemistry calculations
- `Cell`: solely responsible for electrochemistry operations, and does not maintain any form of dynamic state. It is essentially a collection of standalone functions

Additionally, this PR proposes the use of [attrs](https://www.attrs.org/en/stable/index.html). This package allows us much tighter control over our class definitions, which will make the connection with interface components (see #11) much easier. A couple of important notes here:
- Because we have opted to use type declarations here, they are now REQUIRED for all instance variables. If you do not do this, you will end up encountering errors
- Any calculated instance variables that depend on other instance variables must be declared in the definition using `init=False`, then set in the `__attrs_post_init__` function. This seems a bit weird and duplicative, but in practice it provides a clear distinction between fields that are set directly (or set via defaults), and those that are set as side effects. This is one of multiple approaches, see more [here](https://www.attrs.org/en/stable/init.html#hooking-yourself-into-initialization)
- A new mixin class, `FromDictMixin`, was brought over from `floris` to help with instantiation. The result is that class instantiation can be reliably performed using the `from_dict` class method. For example: `cell = Cell.from_dict(cell_dict)`  

Finally, this PR introduces a test suite consisting primarily of unit tests for `Stack` and `Cell`. It adopts a strategy focused more on asserting behavior than on asserting specific results (we should expect more of the latter with #5), with the intention of keeping the tests flexible enough to accommodate upcoming modeling changes while ensuring that the underlying behavior remains the same. One way that this is accomplished is through the use of the [pytest_mock](https://pytest-mock.readthedocs.io/en/latest/) package. Whenever a function has side effects (calls other functions), we can "spy" on the functions that it calls, and ensure that they are called in certain ways. A good example of this is `Stack.update_degradation`, which conditionally delegates to other degradation functions (steady, fatigue, on/off cycling) that actually perform calculations. The corresponding test therefore asserts that those functions are called under the right circumstances (see [test](https://github.com/NREL/electrolyzer/pull/19/files#diff-f45989183f0a186ed095a468229dfd625d0279b09e433cfab103a0d3d0aafe9fR216)). More specific numerical results will be asserted with future regression/integration tests.

**Additional supporting information**

**Test results, if applicable**

### CODE REVIEW

**Comment by jaredthomas68** [comment]
I think this looks great. There are certainly some needs for more comments/docs/docstrings, but those can come later.

**Review by jaredthomas68 — APPROVED** [review]
I think this looks really good. I'd like to talk more about the implications of some of the design choices for integrating with OpenMDAO and obtaining analytic derivatives, but this is definitely good for now from my perspective. We'll also need to add some more comments/docs/docstrings etc down the road. I can't give feedback on the physics here though, so @genevievestarke and @bayc will need to address things from that side.

**Review by genevievestarke — COMMENTED** [review]
I compared the output from the version of "controller_test_draft.py" with the one in the NREL/electrolyzer/develop branch, and they don't quite match up, specifically on the degradation numbers.  What version of the code did you start with?

**Comment by camirmas** [comment]
@genevievestarke originally I think it came from the `milestone/Q2_snapshot` branch in `h2atscale`, and since then nothing else has changed. The supervisor changes that you made in #18 are also in there. So I'm not yet sure where the issue is coming from, as I tried to be careful about not changing the existing implementation

**Pull request merged**
